Add accessibility_trait_for_button rule
realm/SwiftLint pull request #3989
Opened 2022-06-04 04:49 UTC by rcole34

Similar to the [`accessibility_label_for_image`](https://realm.github.io/SwiftLint/accessibility_label_for_image.html) rule, this rule catches another common mistake developers make in SwiftUI that makes their apps less accessible.

The accessibility button and link traits are used to tell assistive technologies that an element is tappable. When an element has one of these traits, VoiceOver will automatically read "button" or "link" after the element's label to let the user know that they can activate it. When using a UIKit `UIButton` or SwiftUI `Button` or `Link`, the button trait is added by default, but when you manually add a tap gesture recognizer to an element, you need to explicitly add the button or link trait. In most cases the button trait should be used, but for buttons that open a URL in an external browser we use the link trait instead. This rule attempts to catch uses of the SwiftUI `.onTapGesture` modifier where the `.isButton` or `.isLink` trait is not explicitly applied.

Per @rwapp, Android will automatically add the button trait when a tap gesture is applied, but until iOS catches up with that I hope for this rule to help remind more people to add the proper accessibility traits!

2022-06-04 05:06 UTC, rcole34 commented
@jpsim @SimplyDanny here's another proposed rule to help catch more accessibility issues in SwiftUI apps! There were some SourceKittenDictionary extensions for parsing SwiftUI modifiers that I copied over from the `accessibility_label_for_image` rule since I was trying to keep the extensions private, but let me know if you think it would be better to move some of these extensions to an internal extension file to centralize them. Appreciate your help reviewing this!

2022-07-08 21:45 UTC, SimplyDanny requested changes
Well done!

> There were some SourceKittenDictionary extensions for parsing SwiftUI modifiers that I copied over from the accessibility_label_for_image rule since I was trying to keep the extensions private, but let me know if you think it would be better to move some of these extensions to an internal extension file to centralize them. Appreciate your help reviewing this!

I would definitely like to ask you to move them into a separate extension for reusability.

2022-07-20 23:42 UTC, rcole34 commented
@SimplyDanny I tried to make a more generic way to check for modifiers with a given name and arguments that can hopefully scale for other SwiftUI linter rules. Happy to work through some revisions of it if you see room for improvement!

2022-09-03 16:29 UTC, SimplyDanny commented
Sorry for the late response! Could you please rebase your branch? Notice that the protocol `AutomaticTestableRule` has been removed. All rules are now automatically tested. The file `AutomaticRuleTests.generated.swift` has been renamed to `GeneratedTests.swift`.

2022-09-03 16:31 UTC, SimplyDanny approved these changes

2022-09-06 21:44 UTC, merged