support extension targets in deployment_target rule
realm/SwiftLint pull request #4011
Opened 2022-06-30 20:49 UTC by tahabebek

Closes #4004

2022-06-30 20:59 UTC, marcelofabri commented
IMO we should default them to their counterpart, e.g. if I set `ios_deployment_target: 13.0`, that should also change `iOSApplicationExtension_deployment_target` unless `iOSApplicationExtension_deployment_target` is explicitly defined

2022-07-01 19:32 UTC, tahabebek commented
@marcelofabri, I have addressed the issue of defaulting.

2022-07-02 07:33 UTC, SimplyDanny requested changes

2022-07-02 07:33 UTC, SimplyDanny commented on CHANGELOG.md
> +* Support iOSApplicationExtension, macOSApplicationExtension, watchOSApplicationExtension, and tvOSApplicationExtension identifiers in `deployment_target` rule. To configure the rule for these identi
Please add line breaks after about every 80 characters and add two additional spaces at the end of the description. They are required to render the CHANGELOG properly:
```suggestion
* Support `iOSApplicationExtension`, `macOSApplicationExtension`,
  `watchOSApplicationExtension`, and `tvOSApplicationExtension` identifiers
  in the `deployment_target` rule. To configure the rule for these identifiers,
  you need to use the keys `iOSApplicationExtension_deployment_target`,
  `macOSApplicationExtension_deployment_target`,
  `watchOSApplicationExtension_deployment_target`, and
  `tvOSApplicationExtension_deployment_target`.  
```

2022-07-02 07:34 UTC, SimplyDanny commented
> @marcelofabri, I have addressed the issue of defaulting.

You may also add this detail to the CHANGELOG entry.

2022-07-03 20:01 UTC, tahabebek commented
@SimplyDanny, I have accepted your suggestions and added the details about defaulting to the changelog entry.

2022-07-05 20:41 UTC, SimplyDanny approved these changes

2022-07-05 20:41 UTC, merged