Fixes SwiftLint support on Xcode Cloud
realm/SwiftLint pull request #4485
Opened 2022-10-28 09:51 UTC by JagCesar

This PR fixes so SwiftLint installed as Xcode Plugin can be used on Xcode Cloud. The problem was that Xcode Cloud doesn't have write access to the `.cachesDirectory`. We solved this by always using ` NSTemporaryDirectory()` if we're being run on a CI.

This will have the side-effect of doing the same on all CI's, but we couldn't come up with a way to distinguish Xcode Cloud from other CI's.

Solved this together with @westerlund

fixes #4484

2022-10-31 15:16 UTC, jpsim commented on Source/SwiftLintFramework/Extensions/Configuration+Cache.swift
> +        if ProcessInfo.processInfo.environment["CI"] == "TRUE" {
CI is a super generic environment variable name. Is there a more reliable way to detect if this is running in an Xcode Cloud environment? I won't want everyone running SwiftLint in their CI to suddenly lose caching.

2022-10-31 15:18 UTC, jpsim requested changes
Calling `NSTemporaryDirectory()` will return a new directory every time, effectively disabling caching of linter results. If we do something like this, it should be by disabling caching explicitly.

2022-10-31 15:23 UTC, westerlund commented
> Calling `NSTemporaryDirectory()` will return a new directory every time, effectively disabling caching of linter results. If we do something like this, it should be by disabling caching explicitly.

Yeah we thought of that and the problem is that we can't send any parameters to Xcode Plugins (as you know) and the only other solution would be to introduce another plugin target which explicitly disables caching, what do you think? Is it better to introduce a second SwiftLintPlugin or disable caching entirely only on Xcode Cloud?

2022-10-31 15:58 UTC, jpsim commented
> If not, then we should find the most reliable way to detect we're running on that platform and disable caching completely.

Here: https://github.com/realm/SwiftLint/blob/0.50.0-rc.3/Source/swiftlint/Commands/Lint.swift#L53

Could be

```swift
ignoreCache: noCache || ProcessInfo.processInfo.environment["SWIFTLINT_DISABLE_CACHE"] == "TRUE"
```

2022-10-31 21:20 UTC, westerlund commented
> Does Xcode Cloud have any way to persist state across CI jobs at all? If not, then we should find the most reliable way to detect we're running on that platform and disable caching completely.

In theory DerivedData will be cached between builds, however it seems like we don't have write access to that path.

> > If not, then we should find the most reliable way to detect we're running on that platform and disable caching completely.
> 
> Here: https://github.com/realm/SwiftLint/blob/0.50.0-rc.3/Source/swiftlint/Commands/Lint.swift#L53
> 
> Could be
> 
> ```swift
> ignoreCache: noCache || ProcessInfo.processInfo.environment["SWIFTLINT_DISABLE_CACHE"] == "TRUE"
> ```

I did some digging and it seems like Xcode Cloud is the only CI setting the variable `CI_BUNDLE_ID`, so expanding on your suggestion it could be something along the lines of:
```swift
ignoreCache: noCache || ProcessInfo.processInfo.environment["CI_BUNDLE_ID"] != nil
```
We'd much rather have this working automatically than manually setting an environment value on the Target itself, what do you think? Would it be reliable enough? At least until we get write permissions on the Xcode Cloud VM.

2022-11-01 14:16 UTC, westerlund commented
> `CI_BUNDLE_ID` is super generic too and possible that either some other CI or even user's dev machines have that set for some reason, and then they'd lose SwiftLint caching. So I'm not comfortable disabling caching based on the presence of that environment variable.
> 
> Xcode Cloud supports setting [custom environment variables](https://developer.apple.com/documentation/xcode/environment-variable-reference), so I'd like to propose that users define the `SWIFTLINT_DISABLE_CACHE` variable and we can check for it in SwiftLint.
> 
> > In addition to predefined environment variables, set custom environment variables in a workflow’s Environment section and access them in your custom build scripts or test actions.

Alright, I'll update the PR and also update the README to reflect this change. Thanks for the input!

2022-11-01 14:59 UTC, jpsim commented
You know what, looking at the [Xcode Cloud docs](https://developer.apple.com/documentation/xcode/environment-variable-reference) again, I think we can be reasonably sure that we're running on Xcode Cloud if all of the following environment variables are set:

```
CI
CI_BUILD_ID
CI_BUILD_NUMBER
CI_BUNDLE_ID
CI_COMMIT
CI_DERIVED_DATA_PATH
CI_PRODUCT
CI_PRODUCT_ID
CI_PRODUCT_PLATFORM
CI_PROJECT_FILE_PATH
CI_START_CONDITION
CI_TEAM_ID
CI_WORKFLOW
CI_WORKSPACE
CI_XCODE_PROJECT
CI_XCODE_SCHEME
CI_XCODEBUILD_ACTION
CI_XCODEBUILD_EXIT_CODE
```

So you could extract a function that determines if we're running on Xcode Cloud.

If someone or some other CI sets all the same environment variables, then I think it's reasonable to disable caching.

2022-11-01 15:16 UTC, westerlund commented
> You know what, looking at the [Xcode Cloud docs](https://developer.apple.com/documentation/xcode/environment-variable-reference) again, I think we can be reasonably sure that we're running on Xcode Cloud if all of the following environment variables are set:
> 
> ```
> CI
> CI_BUILD_ID
> CI_BUILD_NUMBER
> CI_BUNDLE_ID
> CI_COMMIT
> CI_DERIVED_DATA_PATH
> CI_PRODUCT
> CI_PRODUCT_ID
> CI_PRODUCT_PLATFORM
> CI_PROJECT_FILE_PATH
> CI_START_CONDITION
> CI_TEAM_ID
> CI_WORKFLOW
> CI_WORKSPACE
> CI_XCODE_PROJECT
> CI_XCODE_SCHEME
> CI_XCODEBUILD_ACTION
> CI_XCODEBUILD_EXIT_CODE
> ```
> 
> So you could extract a function that determines if we're running on Xcode Cloud.
> 
> If someone or some other CI sets all the same environment variables, then I think it's reasonable to disable caching.

Good idea, we'll go ahead and fix that. I'm glad we could come up with a solution that disables caching automatically , because then we can remove it later when the environment grants us write access!

Ignore my commits, I'll get back with the fix later!

I think it's reasonable to have a section in the README about caching not working on Xcode Cloud, what do you think? I also saw that the README is available in a few other languages than English, how do we properly update all of them?

2022-11-01 15:20 UTC, jpsim commented
> I think it's reasonable to have a section in the README about caching not working on Xcode Cloud, what do you think? I also saw that the README is available in a few other languages than English, how do we properly update all of them?

I don't think this needs a readme entry, and when we update the readme we typically only update the English one, the other ones are occasionally updated by other contributors who speak that language.

2022-11-01 16:32 UTC, jpsim commented
Looks good @JagCesar, thanks for the PR.

I made a few small modifications and will be merging once CI is 🟢

* Moved the check so it also applies when running `analyze`
* Updated `ProcessInfo.isLikelyXcodeCloudEnvironment` to only access `environment` once, in case there's any overhead involved, so it's not done repeatedly.

2022-11-01 16:33 UTC, jpsim approved these changes

2022-11-01 17:00 UTC, merged