Rewrite `opening_brace` rule with SwiftSyntax
realm/SwiftLint pull request #5164
Opened 2023-08-10 09:44 UTC by kishikawakatsumi

Fix https://github.com/realm/SwiftLint/issues/4610
Fix https://github.com/realm/SwiftLint/issues/5114
Fix https://github.com/realm/SwiftLint/issues/3470
Fix https://github.com/realm/SwiftLint/issues/3574
Fix https://github.com/realm/SwiftLint/issues/2632
Fix https://github.com/realm/SwiftLint/issues/3476
Fix https://github.com/realm/SwiftLint/issues/3756

Reworked `opening_brace` rule using SwiftSyntax.
While only violation detection can be implemented by simply visiting `TokenSyntax`, but it is necessary to visit each `*Syntax` to achieve automatic correction. The reason for this is that the whitespace before the brace is not the trivia of the brace, but the trivia of the token before it. So this is a pretty big change.

2023-08-10 10:34 UTC, kishikawakatsumi commented on Source/SwiftLintBuiltInRules/Rules/Style/OpeningBraceRule.swift
> -            Example("guard\n\tlet a = b,\n\tlet c = d\n\twhere a == c else\n{ }"),
Writing a `where` clause to join multiple conditions is no longer permitted in Swift. Therefore, I have removed this test case.

2023-08-10 10:41 UTC, kishikawakatsumi commented on Tests/SwiftLintFrameworkTests/OpeningBraceRuleTests.swift
> -            Example("guard\n\tlet a = b,\n\tlet c = d\n\twhere a == c else\n{ }"),
Writing a `where` clause to join multiple conditions is no longer permitted in Swift. Therefore, I have removed this test case.

2023-08-27 17:01 UTC, SimplyDanny requested changes
Thanks for taking that up!

Please add a CHANGELOG entry to let people know about the fixes.

2023-09-10 14:41 UTC, kishikawakatsumi commented on Source/SwiftLintBuiltInRules/Rules/Style/OpeningBraceRule.swift
> +        if let functionCall = parent?.as(FunctionCallExprSyntax.self) {
Fixed by f07f7f54ce145f886b937f794308c087631f23d0

2023-09-10 15:02 UTC, kishikawakatsumi commented on Source/SwiftLintBuiltInRules/Rules/Style/PreferSelfInStaticReferencesRule.swift
> -                || !node.type.is(SimpleTypeIdentifierSyntax.self)   // Complex or collection type
Fixed 9c57348e4

2023-09-10 15:47 UTC, kishikawakatsumi commented on Source/SwiftLintBuiltInRules/Rules/Style/OpeningBraceRule.swift
> +            var isMultilineFunction: Bool {
Fixed 9b2c86ee8

2023-09-10 16:34 UTC, kishikawakatsumi commented on Source/SwiftLintBuiltInRules/Rules/Style/OpeningBraceRule.swift
> +// swiftlint:disable file_length type_body_length
Fix f0aa7154a39fe43cbeaf4ea6459a50ddc6e2a937

2023-09-11 17:42 UTC, SimplyDanny reviewed
Thanks for the updates!

A few general comments/questions:

1. The implemented corrections will remove comments. While I don't like that, it might be acceptable for the time being. I see a few issues incoming, though.
2. The list of examples is quite long. We typically move them into a separate file when they become too extensive.
3. The examples are not only tests but they also serve as documentation. We should exclude a few from being documented by adding the `excludeFromDocumentation` parameter, especially when they only test special cases.
4. Did you check the OSS findings? I've seen a few which trigger while they shouldn't or don't trigger anymore while they should.

2023-09-11 17:42 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Style/OpeningBraceRule.swift
> +import SwiftSyntaxBuilder
Is this import really needed?

2023-09-11 17:42 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Style/OpeningBraceRule.swift
> +            """),
The common indentation style for corrected examples in SwiftLint would be like:
```suggestion
                Example("""
                for a in b {

                }
                """),
```

2023-12-02 00:12 UTC, SimplyDanny commented
Rebased, resolved conflicts, adapted code to current state of the project, simplified a little.

What's left:

- [x] Resolve review comments
- [ ] Fix changelog
- [ ] Check OSS findings

2023-12-02 11:21 UTC, merged