#5461 added ib_segue_action case in TypeContent
realm/SwiftLint pull request #5524
Opened 2024-04-02 15:19 UTC by dk-talks

Hey! I have added a new case to TypeContent enum for ib_segue_action. And also adapted the change in [TypeContentsOrderRule.swift](https://github.com/realm/SwiftLint/blob/main/Source/SwiftLintBuiltInRules/Rules/Style/TypeContentsOrderRule.swift).

2024-04-06 15:21 UTC, SimplyDanny requested changes

2024-04-06 15:21 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/TypeContentsOrderConfiguration.swift
>          [.deinitializer]
@dk-talks: There is a comma missing here.

2024-04-07 10:46 UTC, SimplyDanny requested changes
Thanks! This needs some tests. See `TypeContentsOrderRuleTests`.

Also, you need to update the test reference for `IntegrationTests.testDefaultConfigurations` to make the build pass.

2024-04-07 10:46 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/TypeContentsOrderConfiguration.swift
> +        [.ibSegueAction]
This needs to be removed. We try to avoid changing the defaults subsequently if possible.

2024-04-09 06:10 UTC, dk-talks commented
Hi, @SimplyDanny still the build is not passing, is there something else needed to be done?

2024-04-09 08:41 UTC, SimplyDanny commented
> Hi, @SimplyDanny still the build is not passing, is there something else needed to be done?

Now that you have removed the entry from the default list, the test reference update needs to be reverted.

2024-04-09 14:25 UTC, dk-talks commented
Hey @SimplyDanny. Now that the build has passed, is there anything else needs to be done or is it enough to merge and close the issue?

2024-04-13 09:10 UTC, SimplyDanny commented
> Hey @SimplyDanny. Now that the build has passed, is there anything else needs to be done or is it enough to merge and close the issue?

1. This change needs tests. See `TypeContentsOrderRuleTests`.
2. A changelog entry needs to be added. See `CHANGELOG.md`.

2024-12-14 17:24 UTC, SimplyDanny approved these changes

2024-12-14 23:02 UTC, merged

2025-01-13 11:38 UTC, guillaumealgis commented
Hi, thanks for adding this new case to the `type_contents_order` rule :)

It seems [the documentation](https://realm.github.io/SwiftLint/type_contents_order.html) has not been updated, and I could not find where `ib_segue_action` is located in [the default configuration for this rule](https://github.com/realm/SwiftLint/blob/f045130e3e8e5bcaf09cc336b7b947d4bdc4b7c1/Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/TypeContentsOrderConfiguration.swift#L30), making it difficult to know where SwiftLint expects me to put my `@IBSegueAction` methods 😕

2025-01-13 18:14 UTC, SimplyDanny commented
> Hi, thanks for adding this new case to the `type_contents_order` rule :)
> 
> It seems [the documentation](https://realm.github.io/SwiftLint/type_contents_order.html) has not been updated, and I could not find where `ib_segue_action` is located in [the default configuration for this rule](https://github.com/realm/SwiftLint/blob/f045130e3e8e5bcaf09cc336b7b947d4bdc4b7c1/Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/TypeContentsOrderConfiguration.swift#L30), making it difficult to know where SwiftLint expects me to put my `@IBSegueAction` methods 😕
> 
> EDIT: It seems that putting the `@IBSegueAction` methods at the end of the enclosing type's implementation makes SwiftLint happy.

We intentionally didn't specify a default expectation because the new type was added on top of the already existing ones. And what's not explicitly specified is expected last by the rule.

@guillaumealgis: Do you think a default would be reasonable (also for documentation purposes) instead of leaving it unspecified? If so, what would be a decent order? Is putting it on the same level as `@IBAction` a good idea?

2025-01-14 13:43 UTC, guillaumealgis commented
> Do you think a default would be reasonable (also for documentation purposes) instead of leaving it unspecified? 

I think SwiftLint should explicitly define an order for all defined cases. This makes the expected position of the elements clearer for everyone.

I have honestly no strong opinion on where to put `ib_segue_action` in the list. Same level / right after `ib_action` seems fine, between `other_method` and `subscript` would be fine also, end of list is not outrageous 🤷🏼‍♂️

> what's not explicitly specified is expected last by the rule

Seems pretty logical, but it's not documented, so when SwiftLint started complaining after I updated it was not clear where I should put my code to satisfy it :)

2025-01-14 19:47 UTC, SimplyDanny commented
> I have honestly no strong opinion on where to put `ib_segue_action` in the list. Same level / right after `ib_action` seems fine, between `other_method` and `subscript` would be fine also, end of list is not outrageous 🤷🏼‍♂️

Same level as `ib_action` should be fine then: #5956.