Fix type inside shell script in README.md
realm/SwiftLint pull request #5621
Opened 2024-06-11 16:41 UTC by miltenkot

I notice wrong typo which doesn't works properly.

2024-06-11 18:37 UTC, SimplyDanny requested changes
I don't see a typo in the original word. "Validation" is correct.

2024-06-12 07:16 UTC, miltenkot commented
> I don't see a typo in the original word. "Validation" is correct.

Yes, however, does not work correctly. I checked with this article, and it should be entered with a misspelling (validataion) to work with CI (Xcode Cloud). (https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305/10)

2024-06-12 21:08 UTC, SimplyDanny commented
> > I don't see a typo in the original word. "Validation" is correct.
> 
> Yes, however, does not work correctly. I checked with this article, and it should be entered with a misspelling (validataion) to work with CI (Xcode Cloud). (https://forums.swift.org/t/telling-xcode-14-beta-4-to-trust-build-tool-plugins-programatically/59305/10)

I see, that wasn't obvious to me. It's still hard to approve a PR that introduces a typo ... I've never done that before. 😅

2024-06-12 21:08 UTC, SimplyDanny approved these changes

2024-06-22 17:51 UTC, merged