make NoEmptyBlock rule to opt-in and add configuration
realm/SwiftLint pull request #5685
Opened 2024-07-21 08:34 UTC by Ueeek

2024-07-21 10:56 UTC, SimplyDanny requested changes
Thanks for taking this up!

Besides me inline comments, there are two more general remarks:

* Please add some examples that show how the options work. A configuration deviating from the default will be added now into the rendered examples in the documentation.
* The rule in its current state doesn't consider `AccessorBlock`s at all.

2024-07-21 10:56 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoEmptyBlockRule.swift
> +            return .accessorBodies
It's okay to have it separate, but it could also be included in `.functionBodies`.

2024-07-21 10:56 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoEmptyBlockRule.swift
> +        switch kind {
```suggestion
        switch parent?.kind {
```

Then you can make use of a `switch` expression and leave out the `return` keywords. 😉

2024-07-21 10:56 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoEmptyBlockRule.swift
> +            return .statementBlocks
```suggestion
        case .forStmt, .doStmt, .whileStmt, .repeatStmt, .ifExpr, .catchClause, .deferStmt:
            return .statementBlocks
        case .guardStmt:
            return nil
```

That way, you can skip the check in line 104.

2024-07-21 10:56 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/RuleConfigurations/NoEmptyBlockConfiguration.swift
> +    private(set) var disabledBlockTypes: [CodeBlockType] = []
Please let the key's name coincide with the variable name:
```suggestion
    @ConfigurationElement(key: "disabled_block_types")
    private(set) var disabledBlockTypes: [CodeBlockType] = []
```
Later, we want to have the keys be inferred from the variable names.

2024-07-21 14:40 UTC, Ueeek commented
@SimplyDanny 
Thank you for giving kind feedback.
I fixed all the points you mentioned except for the one below!

> The rule in its current state doesn't consider AccessorBlocks at all.
Is this mean to add more examples related to "Accessor Blocks"?
It would be very appreciated if you could help me understand the comment well 🙇 
Thank you!

2024-07-21 15:21 UTC, SimplyDanny commented
> > The rule in its current state doesn't consider AccessorBlocks at all.
> 
> Is this mean to add more examples related to "Accessor Blocks"?
> 
> It would be very appreciated if you could help me understand the comment well 🙇 

I think that the rule wouldn't trigger in the example

```swift
struct S {
  var i: Int {}
}
```

But this is actually invalid Swift code anyway. So you can ignore my comment. Sorry for the confusion.

2024-07-21 15:32 UTC, SimplyDanny requested changes

2024-07-21 15:32 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoEmptyBlockRule.swift
> +            """, configuration: ["disabled_block_types": ["statement_blocks"]]),
Let's merge all the examples for one specific type of block into one, so that the rendering is a bit more dense.

2024-07-21 15:32 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/NoEmptyBlockRule.swift
> +            init() {}
All examples should be valid Swift. `init`, `deinit` and `defer` need some declaration around them.

2024-07-22 16:33 UTC, SimplyDanny approved these changes
Thanks for all the updates!

2024-07-22 16:34 UTC, merged

2024-07-23 00:52 UTC, Ueeek commented
@SimplyDanny Thank you for kind feedbacks!