Add minimum_swiftlint_version as a configuration option
realm/SwiftLint pull request #5694
Opened 2024-07-24 15:32 UTC by alex-taffe

Currently, the configuration supports a `swiftlint_version` option. This option does not work for our workflow because we have many branches that may not be up to date with main/master. However, there are breaking changes that occur in SwiftLint, such as `redundant_optional_initialization` changing between 0.53.0 and 0.55.1, causing our team to not have consistency in their linting.

This adds a new `minimum_swiftlint_version` that will compare to the current version installed and throw a warning/error if the installed version is older than the version mandated by the configuration document, ex:

> warning: Currently running SwiftLint 0.55.1 but configuration specified minimum version 0.55.3.

The syntax is as follows:
```
minimum_swiftlint_version: 0.55.5
```

2024-07-31 01:31 UTC, alex-taffe commented
@SimplyDanny @mildm8nnered  if you could take a look at this when you get a chance, thanks!

2024-07-31 20:36 UTC, SimplyDanny commented
I see where you are coming from and why this would help, yet I was wondering whether a new separate key is really the way to go. The list is continuously growing and there is the problem of conflicting options. What about `minimum_swiftlint_version: 0.54.0` and `swiftlint_version: 0.53.0` for example? So there should probably be some consistency checks.

What I was thinking about is an extension of `swiftlint_version` in a way that it supports both fixed versions and a range of version given a minimum version. Something like the syntax `swiftlint_version: >=0.54.0` could be conceivable. What's your opinion on that?

2024-07-31 20:47 UTC, alex-taffe commented
Yeah I think I actually like that better, what're your thoughts on syntax? I kinda like [Dart's](https://dart.dev/tools/pub/dependencies). Traditional and carrot. Then if we can't parse, just throw a fatal error.

<img width="262" alt="image" src="https://github.com/user-attachments/assets/e33a1839-16be-4c19-9163-53a6ed064cb4">


<img width="923" alt="image" src="https://github.com/user-attachments/assets/9f4f0b1b-e88a-4bc5-8c0b-4ecb79cc3d60">

2024-07-31 20:51 UTC, alex-taffe commented
Also what's the minimum version of macOS that SwiftLint supports? Would love to use new SwiftRegex but it's macOS 13 or newer only

2024-07-31 21:13 UTC, SimplyDanny commented
> Also what's the minimum version of macOS that SwiftLint supports? Would love to use new SwiftRegex but it's macOS 13 or newer only

SwiftLint still supports macOS 12. We'd need good reasons to change that. While I fancy as well with SwiftRegex, it's not enough reason to change the minimum deployment version. But that might change when macOS 15 is out.

About the syntax: I personally don't like the caret style so much. Only the three variants

* `0.54.0`
* `>0.54.0`
* `>=0.54.0`

seem to be enough. There is no good reason for `<0.54.0` or `<=0.54.0`, is there?

2024-07-31 21:34 UTC, alex-taffe commented
In practice I’m guessing the less than or inclusive versions wouldn’t actually be used much (I doubt we ever will), but doesn’t seem like that much more work so might as well just do it while I’m in there. I’m fine with omitting caret syntax

2024-07-31 21:40 UTC, SimplyDanny commented
In your implementation it could be helpful to know that `Version` objects are `Comparable`. 😉

2024-08-01 15:12 UTC, alex-taffe commented
@SimplyDanny updated

2024-08-01 19:02 UTC, SimplyDanny requested changes
Good starting point! Please also add some tests for all the cases.

2024-08-01 19:02 UTC, SimplyDanny commented on Source/SwiftLintCore/Models/Configuration.swift
> +            if versionString.starts(with: ">=") {
You could assign the variables directly making use of an `if` expression.

2024-08-05 14:51 UTC, alex-taffe commented
@SimplyDanny how do you suggest I approach tests on this? AFAIK, XCTest can't handle pulling out info from stdout nor can it intercept calls to `abort()`. I could refactor the method so it throws out an error enum with an intermediary that actually calls abort, but seems like a lot of boilerplate. Does bazel have some other better way to tackle this?

2024-08-13 02:26 UTC, alex-taffe commented
@SimplyDanny just seeing if you had any thoughts on this. Apologies for the follow up, this is just rapidly causing chaos amongst our 9000 internal branches (which is a whole separate issue but)

2024-08-18 14:04 UTC, SimplyDanny requested changes

2024-08-18 14:04 UTC, SimplyDanny commented on Source/SwiftLintCore/Models/Configuration.swift
> +                    "configuration specified \(errorDifferentiatorString) \(versionString)."
Prefer a string block.

2024-08-18 14:04 UTC, SimplyDanny commented on Source/SwiftLintCore/Models/Configuration.swift
> +            guard versionString.range(of: #"^\d+\.\d+\.\d+$"#, options: .regularExpression) != nil else {
Feels like the `Version` initializer should check this.

2024-08-19 20:41 UTC, SimplyDanny reviewed
Some more style issues ...

2024-08-19 20:41 UTC, SimplyDanny commented on Source/SwiftLintCore/Models/Configuration.swift
> +            """
Indent:
```suggestion
                error: swiftlint_version syntax invalid.
                Please specify a version as follows:
                0.54.0
                >0.54.0
                >=0.54.0
                <0.54.0
                <=0.54.0
                """
```

2024-08-19 20:41 UTC, SimplyDanny commented on Source/SwiftLintCore/Models/Configuration.swift
> +            )
```suggestion
            queuedFatalError(invalidVersionString)
```

2024-08-19 20:41 UTC, SimplyDanny commented on Source/SwiftLintCore/Models/Configuration.swift
> +                    "configuration specified \(errorDifferentiatorString) \(versionString)."
```suggestion
                    """
                    warning: Currently running SwiftLint \(Version.current.value) but \
                    configuration specified \(errorDifferentiatorString) \(versionString).
                    """
```

2024-08-19 21:24 UTC, alex-taffe commented
@SimplyDanny yeah sorry I pushed a bunch of stuff earlier then got distracted with some fires at work, I was working on refactoring into a struct anyways

2026-05-27 15:13 UTC, alex-taffe commented
We went a different direction on this, closing

2026-05-27 15:13 UTC, closed without merging