add support file Xcode input file lists
realm/SwiftLint pull request #5790
Opened 2024-09-12 09:09 UTC by BlueVirusX

adds option "--use-script-input-file-lists"
adds parsing of .xcfilelist files

2024-10-24 17:15 UTC, SimplyDanny requested changes
Seems reasonable to add this. Thanks for the implementation!

I've added a few remarks. Please take them into account.

2024-10-24 17:15 UTC, SimplyDanny commented on Source/SwiftLintFramework/Configuration+CommandLine.swift
> +            let files = options.useScriptInputFiles ? try scriptInputFiles() : try scriptInputFileLists()
```suggestion
            let files = try options.useScriptInputFiles 
                ? scriptInputFiles()
                : scriptInputFileLists()
```

2024-10-24 17:15 UTC, SimplyDanny commented on CHANGELOG.md
> +  [#5790](https://github.com/realm/SwiftLint/pull/5790)
IDs refer to issues not to pull request. The PR ID will be attached to the commit message automatically upon merge.

```suggestion

* Support reading files to lint from Input File Lists provided
  by Run Script Build Phases in Xcode using the command-line
  argument `--use-script-input-file-lists`.  
  [BlueVirusX](https://github.com/BlueVirusX)
```

2024-10-24 17:15 UTC, SimplyDanny commented on README.md
> +`SCRIPT_INPUT_FILE_LIST_{SCRIPT_INPUT_FILE_LIST_COUNT - 1}`.
```suggestion
`SCRIPT_INPUT_FILE_{SCRIPT_INPUT_FILE_COUNT - 1}`.
Similarly, files can be read from file lists by passing
the option `--use-script-input-file-lists` and setting the
following instance variables: `SCRIPT_INPUT_FILE_LIST_COUNT`
and `SCRIPT_INPUT_FILE_LIST_0`, `SCRIPT_INPUT_FILE_LIST_1`, ...,
`SCRIPT_INPUT_FILE_LIST_{SCRIPT_INPUT_FILE_LIST_COUNT - 1}`.
```

2024-10-24 17:15 UTC, SimplyDanny commented on Source/swiftlint/Common/LintOrAnalyzeArguments.swift
> +    @Flag(help: "Read SCRIPT_INPUT_FILE_LIST* environment variables as file list.")
```suggestion
    @Flag(help: "Read SCRIPT_INPUT_FILE_LIST* environment variables as file lists.")
```

2024-10-24 17:15 UTC, SimplyDanny commented on Source/SwiftLintFramework/Configuration+CommandLine.swift
> +private func scriptInputFileLists() throws -> [SwiftLintFile] {
```suggestion
private func readFilesFromScriptInputFileLists() throws -> [SwiftLintFile] {
```

Please rename the existing method accordingly.

2024-10-24 17:15 UTC, SimplyDanny commented on Source/SwiftLintFramework/Configuration+CommandLine.swift
> +    }
Extract this to a method accepting a variable name and retuning an integer.

2024-10-24 17:15 UTC, SimplyDanny commented on Source/SwiftLintFramework/Configuration+CommandLine.swift
> +        var swiftLintFiles: [SwiftLintFile] = []
```suggestion
        var filesToLint: [SwiftLintFile] = []
```

2024-10-25 10:34 UTC, BlueVirusX commented
Thanks for the review @SimplyDanny!

2024-10-25 10:34 UTC, SimplyDanny approved these changes
Perfect! Thanks for the updates.

2024-10-25 10:34 UTC, SimplyDanny commented on Source/SwiftLintFramework/Configuration+CommandLine.swift
> +private func fileCount(for envVar: String) throws -> Int {
```suggestion
private func fileCount(from envVar: String) throws -> Int {
```

2024-10-25 10:57 UTC, merged