Dont trigger for non-optional type casting, or for optional types
realm/SwiftLint pull request #5805
Opened 2024-09-21 11:18 UTC by mildm8nnered

Addresses #5802

WIP

2024-10-03 14:24 UTC, Naveen-C-Ramachandrappa approved these changes

2024-10-07 21:21 UTC, SimplyDanny requested changes

2024-10-07 21:21 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/PreferTypeCheckingRule.swift
> +            Example("bar as Foo? != nil"),
This line is a duplicate.

2024-10-07 21:21 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/PreferTypeCheckingRule.swift
> +            Example("bar as? Foo? != nil"),
This could actually be written as `bar is Foo`, couldn't it?

2024-10-07 21:21 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/PreferTypeCheckingRule.swift
> +           asExpr.type.is(OptionalTypeSyntax.self) == false,
```suggestion
           !asExpr.type.is(OptionalTypeSyntax.self),
```

2024-10-07 21:21 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/PreferTypeCheckingRule.swift
This rule doesn't consider that `!=` is commutative. So cases like `nil != bar as? Int` are not found.

2024-10-08 18:14 UTC, mildm8nnered commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/PreferTypeCheckingRule.swift
> +            Example("bar as Foo? != nil"),
🤦

2024-10-08 18:19 UTC, mildm8nnered commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/PreferTypeCheckingRule.swift
That is true - I'm not sure how common that is, but it should be pretty easy to cover

2024-10-11 17:39 UTC, SimplyDanny approved these changes

2024-10-11 17:40 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Idiomatic/PreferTypeCheckingRule.swift
There's at least one finding. 😉

2024-10-11 18:15 UTC, merged