Fix: TipKit rule triggers an empty_count violation
realm/SwiftLint pull request #5918
Opened 2024-12-28 05:37 UTC by Ueeek

resolve #5883 
Skip TipKit RuleMacro in EmptyCountRule

2025-01-05 12:12 UTC, SimplyDanny requested changes
Thank you! Looks good in general, yet we can be even more restrictive in the check for the `#Rule` macro.

2025-01-05 12:12 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +        self.trailingClosure != nil
Let's be even more restrictive here:
```suggestion
        macroName.text == "Rule" &&
        arguments.count == 1 &&
        trailingClosure.map { $0.statements.onlyElement?.item.is(ReturnStmtSyntax.self) == false } ?? false
```

2025-01-05 12:12 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +                Example("let predicate =  #Predicate<SwiftDataModel> { $0.list.isEmpty }"),
Instead of `#Predicate<SwiftDataModel>` you may also use any other (simpler) macro that's not `#Rule`.

2025-01-05 14:30 UTC, Ueeek commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +                Example("let predicate =  #Predicate<SwiftDataModel> { $0.list.isEmpty }"),
Thank you for the suggestion!
I used "#ExampleMacro" as an example of Macro, referring NoMagicNumberRule.
Or, is it better to use an actual example?(e.g. #Preview?)

2025-01-05 15:20 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +                Example("let predicate =  #Predicate<SwiftDataModel> { $0.list.isEmpty }"),
`#ExampleMacro` is great. The only reason I was suggesting another name is to keep the examples very simple and reduced down to the significant aspects. Otherwise, the name or its actual existence is not important as long as it's something different than `#Rule` to have a valid test case.

What comes to my mind now is that we should also test against `#Rule` without any arguments or more than one, the macro with a non-trailing closure, a return statement inside or more than one statement, ...

You can exclude these test cases from appearing in the documentation for simplicity by adding the argument `excludeFromDocumentation: true`. Only leave the ones you have now and skip the others as they are not helping users in understanding.

2025-01-05 15:21 UTC, SimplyDanny commented
Please rebase your branch to resolve the conflict.

2025-01-06 14:33 UTC, Ueeek commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +                Example("let predicate =  #Predicate<SwiftDataModel> { $0.list.isEmpty }"),
Nice suggestion, let me add the following tests.
* #Rule without any arguments
* #Rule with more than 1 argument
* #Rule with non-trailing closure
* #Rule with  multiple trailing closure
* #Rule with a closure with the return statement
* #Rule with a closure with multiple statements.

So far, writing the code of the above test cases with the #Rule macro from the Tips Kit results in a compile error.
However, we added the tests for the following reasons. Do I understand correctly? 🤔
* To cover all the conditional branches introduced in this PR.
* To prepare for the possibility that the #Rule macro might support {no/multiple} {arguments/closures} in the future.

2025-01-06 15:48 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +                Example("let predicate =  #Predicate<SwiftDataModel> { $0.list.isEmpty }"),
Yes, we want to make very sure that the rule only ignores the TipKit `#Rule` macro, not any other `#Rule` macro. To know for sure, the rule would need full type information. That's expensive, so we try to encode all the syntactic details we know about the macro in order to reduce false positives. That's not 100% even now, but close enough.

The compiler complains about these cases for TipKit's `#Rule` macro. There could be other `#Rule` macros which are not as strict. We still want to check them.

If you remove `import TipKit` and define your own `#Rule` macro, the compiler will be happy. That's what you need to imagining as a test setup (without specifying that explicitly).

Makes sense?

2025-01-06 15:52 UTC, SimplyDanny commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +            """),
To verify the correction mechanism, one test case is enough. We don't need to repeat all of them here again.

2025-01-07 09:46 UTC, Ueeek commented on Source/SwiftLintBuiltInRules/Rules/Performance/EmptyCountRule.swift
> +                Example("let predicate =  #Predicate<SwiftDataModel> { $0.list.isEmpty }"),
Yes! Thank you for explain it! I'm learning lot from you. 😄

2025-01-07 12:33 UTC, SimplyDanny approved these changes
Two more nits. Then this is good to go. 👍

2025-01-07 13:58 UTC, SimplyDanny commented on CHANGELOG.md
> +* Ignore TipKit's' `#Rule` macro in `empty_count` rule.
```suggestion
* Ignore TipKit's `#Rule` macro in `empty_count` rule.  
```

2025-01-07 14:22 UTC, merged